### ISSUE TITLE
Unable to handle transient faults in gRPC channel used by CerbosClient.

### ISSUE THREAD

**Issue by markdBC** [cerbos/cerbos-sdk-net#91]
Hi,

In our production environment, we are running Cerbos containers in AWS EKS. Our application code is also running in EKS, and they connect to the Cerbos containers with gRPC via the Cerbos .NET SDK provided in this repository.

Occasionally (about once an hour), we see `Grpc.Core.RpcExceptions` that cause the Cerbos calls to fail:

```
System.Exception: Failed to check resources: $Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. IOException: The request was aborted. Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).", DebugException="System.IO.IOException: The request was aborted.")
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Cerbos.Api.V1.Svc.CerbosService.CerbosServiceClient.CheckResources(CheckResourcesRequest request, CallOptions options)
   at Cerbos.Api.V1.Svc.CerbosService.CerbosServiceClient.CheckResources(CheckResourcesRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Cerbos.Sdk.CerbosBlockingClient.CheckResources(CheckResourcesRequest request)
   at Cerbos.Sdk.CerbosBlockingClient.CheckResources(CheckResourcesRequest request)
   at Cerbos.Sdk.CerbosBlockingClient.CheckResources(String requestId, Principal principal, ResourceAction resourceAction)
```

This is probably due to some transient network fault, and is not directly related to Cerbos. One recommended way to deal with transient network faults in the gRPC channel is to configure retries (https://learn.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-7.0). However, this involves providing a `GrpcChannelOptions` object to the `GrpcChannel` object upon construction. Because of the way the `CerbosClientBuilder` class builds `CerbosClient` objects, this is not currently possible.

Please could you add some method (e.g. `WithDefaultGrpcChannelOptions(GrpcChannelOptions)`) that allows library users to configure the gRPC channel used by the `CerbosClient`?

**Comment by markdBC** [comment]
Thanks for merging #92. Closing this issue.
